#!/usr/bin/env python3
"""Generator: widget description → what the plasmoid understands.

The description layer (`schema/widget.json` + `schema/blocks.json`) does not depend
on the engine. Here it is validated and turned into a JS module inside the package:
QML cannot read the file — plasmashell forbids XHR to file://, while importing .js works.
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = ROOT / "schema"
OUT = ROOT / "monitor" / "package" / "contents" / "code" / "description.js"

TYPES = {
    "bool": lambda v: isinstance(v, bool),
    "int": lambda v: isinstance(v, int) and not isinstance(v, bool),
    "string": lambda v: isinstance(v, str),
    "stringlist": lambda v: isinstance(v, list) and all(isinstance(x, str) for x in v),
}


def load(name):
    with (SCHEMA / name).open(encoding="utf-8") as f:
        return json.load(f)


def check(widget, vocab):
    """Return a list of errors. An empty list means the description is valid."""
    errors = []
    seen = set()
    for i, block in enumerate(widget.get("blocks", [])):
        where = f"block {i} (id={block.get('id', '?')})"
        bid = block.get("id")
        if not bid:
            errors.append(f"{where}: no id")
        elif bid in seen:
            errors.append(f"{where}: duplicate id")
        else:
            seen.add(bid)

        btype = block.get("type")
        spec = vocab.get(btype)
        if spec is None:
            errors.append(f'{where}: unknown type "{btype}" — not in blocks.json')
            continue

        params = spec.get("params", {})
        for key, value in (block.get("params") or {}).items():
            if key not in params:
                errors.append(f'{where}: parameter "{key}" is not declared by type "{btype}"')
                continue
            want = params[key]["type"]
            if not TYPES[want](value):
                errors.append(f'{where}: parameter "{key}" must be {want}, got {value!r}')
    return errors


def fill(widget, vocab):
    """Fill parameters with the default values from the vocabulary."""
    out = []
    for block in widget["blocks"]:
        spec = vocab[block["type"]]
        params = {k: v["default"] for k, v in spec.get("params", {}).items()}
        params.update(block.get("params") or {})
        out.append({
            "id": block["id"],
            "type": block["type"],
            "enabled": block.get("enabled", True),
            "params": params,
        })
    return out


def main():
    widget = load("widget.json")
    vocab = {k: v for k, v in load("blocks.json").items() if not k.startswith("_")}

    errors = check(widget, vocab)
    if errors:
        print("The description is invalid:", file=sys.stderr)
        for e in errors:
            print("  ✗ " + e, file=sys.stderr)
        return 1

    blocks = fill(widget, vocab)
    dump = lambda o: json.dumps(o, ensure_ascii=False, indent=2)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        ".pragma library\n"
        "// Generated by monitor/generate.py from schema/*.json — do not edit by hand.\n"
        f"var BLOCKS = {dump(blocks)}\n\n"
        f"var VOCAB = {dump(vocab)}\n",
        encoding="utf-8",
    )
    print(f"  ✓ description (blocks: {len(blocks)}) → {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
